"""A4 PDF layout: optional cover, one coloring page per sheet, optional outlined caption,
small attribution footer (source domain or generation provider). Also writes report.md."""

from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.parse import urlparse

from PIL import Image
from reportlab.lib.colors import Color, black
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen.canvas import Canvas

SKILL_DIR = Path(__file__).resolve().parents[2]
FONT_NAME = "ColoringFont"
CAPTION_H = 24 * mm
FOOTER_H = 5 * mm
FOOTER_GRAY = Color(0.55, 0.55, 0.55)

LABELS = {
    "uk": {"found": "Джерело", "converted": "Перетворено з", "generated": "Згенеровано",
           "page": "Сторінка", "subject": "Тема", "origin": "Походження", "status": "Статус",
           "included": "у PDF", "skipped": "пропущено", "report": "Звіт"},
    "en": {"found": "Source", "converted": "Converted from", "generated": "Generated by",
           "page": "Page", "subject": "Subject", "origin": "Origin", "status": "Status",
           "included": "in PDF", "skipped": "skipped", "report": "Report"},
}


def build_pdf(job_dir: Path, cfg: dict) -> Path:
    """Lay out accepted pages of a job into <job_dir>/<slug>.pdf and write report.md.

    A page is included when it has a final image, is not `failed` and was not
    rejected by the inspector. Raises ValueError when no page qualifies.
    """
    job_path = job_dir / "job.json"
    job = json.loads(job_path.read_text())
    spec = job["spec"]
    labels = LABELS.get(spec.get("language", "en"), LABELS["en"])
    pdf_cfg = cfg["pdf"]

    pages = [json.loads(p.read_text()) for p in sorted(job_dir.glob("pages/*/page.json"))]
    included, skipped = [], []
    for page in pages:
        page_dir = job_dir / "pages" / f"{page['n']:02d}"
        reason = _skip_reason(page, page_dir)
        if reason:
            skipped.append((page, reason))
        else:
            included.append((page, page_dir / page["final"]["path"]))
    if not included:
        raise ValueError("no pages to include: " + "; ".join(f"{p['n']}: {r}" for p, r in skipped))

    font_path = SKILL_DIR / pdf_cfg["font"]
    if FONT_NAME not in pdfmetrics.getRegisteredFontNames():
        pdfmetrics.registerFont(TTFont(FONT_NAME, str(font_path)))

    title = spec.get("title") or included[0][0]["subject"]
    out = job_dir / f"{_slug(title)}.pdf"
    canvas = Canvas(str(out), pagesize=A4)
    canvas.setTitle(title)
    canvas.setCreator("coloring plugin")

    margin = pdf_cfg["margin_mm"] * mm
    if spec.get("cover") and len(included) > 1:
        _draw_cover(canvas, title, [img for _, img in included], margin)
    for page, image in included:
        caption = page.get("caption") if spec.get("captions") else None
        footer = _attribution(page["final"], labels) if pdf_cfg.get("footer_attribution") else None
        _draw_page(canvas, image, spec.get("orientation", "auto"), margin, caption, footer)
    canvas.save()

    _write_report(job_dir, title, included, skipped, labels, out)
    job.update(status="done", pdf=str(out),
               included=[p["n"] for p, _ in included], skipped=[p["n"] for p, _ in skipped])
    job_path.write_text(json.dumps(job, ensure_ascii=False, indent=2))
    return out


def _skip_reason(page: dict, page_dir: Path) -> str | None:
    final = page.get("final")
    if page.get("status") == "failed":
        return "failed"
    if not final or not final.get("path"):
        return "no final image"
    if not (page_dir / final["path"]).exists():
        return "final image missing on disk"
    if (page.get("inspection") or {}).get("verdict") == "reject":
        return "rejected by inspector"
    return None


def _image_size(path: Path) -> tuple[int, int]:
    with Image.open(path) as im:
        return im.size


def _fit(w: float, h: float, box_w: float, box_h: float) -> tuple[float, float]:
    s = min(box_w / w, box_h / h)
    return w * s, h * s


def _draw_page(canvas: Canvas, image: Path, orientation: str, margin: float,
               caption: str | None, footer: str | None) -> None:
    iw, ih = _image_size(image)
    is_landscape = orientation == "landscape" or (orientation == "auto" and iw > ih)
    pw, ph = landscape(A4) if is_landscape else A4
    canvas.setPageSize((pw, ph))

    bottom = margin + (FOOTER_H if footer else 0) + (CAPTION_H if caption else 0)
    box_w, box_h = pw - 2 * margin, ph - margin - bottom
    dw, dh = _fit(iw, ih, box_w, box_h)
    canvas.drawImage(str(image), (pw - dw) / 2, bottom + (box_h - dh) / 2, dw, dh)

    if caption:
        _draw_caption(canvas, caption, pw / 2, margin + (FOOTER_H if footer else 0), pw - 2 * margin)
    if footer:
        canvas.setFillColor(FOOTER_GRAY)
        canvas.setFont(FONT_NAME, 7)
        canvas.drawCentredString(pw / 2, margin, footer[:150])
    canvas.showPage()


def _draw_caption(canvas: Canvas, text: str, cx: float, y0: float, max_w: float) -> None:
    """Outlined (stroke-only) letters, so the caption can be colored too."""
    size = 40.0
    while size > 14 and pdfmetrics.stringWidth(text, FONT_NAME, size) > max_w:
        size -= 2
    canvas.saveState()
    canvas.setStrokeColor(black)
    canvas.setLineWidth(1.4)
    t = canvas.beginText()
    t.setFont(FONT_NAME, size)
    t.setTextRenderMode(1)
    t.setTextOrigin(cx - pdfmetrics.stringWidth(text, FONT_NAME, size) / 2,
                    y0 + (CAPTION_H - size * 0.72) / 2)
    t.textLine(text)
    canvas.drawText(t)
    canvas.restoreState()


def _draw_cover(canvas: Canvas, title: str, images: list[Path], margin: float) -> None:
    pw, ph = A4
    canvas.setPageSize(A4)
    _draw_caption(canvas, title, pw / 2, ph - margin - CAPTION_H - 10 * mm, pw - 2 * margin)

    cols = 2 if len(images) <= 4 else 3
    rows = -(-len(images) // cols)
    gap = 6 * mm
    top = ph - margin - CAPTION_H - 20 * mm
    cell_w = (pw - 2 * margin - (cols - 1) * gap) / cols
    cell_h = min(cell_w * 1.414, (top - margin - (rows - 1) * gap) / rows)
    canvas.setLineWidth(0.8)
    for i, image in enumerate(images):
        r, c = divmod(i, cols)
        x = margin + c * (cell_w + gap)
        y = top - (r + 1) * cell_h - r * gap
        canvas.roundRect(x, y, cell_w, cell_h, 4 * mm)
        iw, ih = _image_size(image)
        dw, dh = _fit(iw, ih, cell_w - 6 * mm, cell_h - 6 * mm)
        canvas.drawImage(str(image), x + (cell_w - dw) / 2, y + (cell_h - dh) / 2, dw, dh)
    canvas.showPage()


def _attribution(final: dict, labels: dict) -> str | None:
    origin = final.get("origin")
    if origin == "generated":
        return f"{labels['generated']}: {final.get('provider') or '?'}"
    url = final.get("source_page") or final.get("source_url")
    if origin in ("found", "converted") and url:
        return f"{labels[origin]}: {urlparse(url).netloc or url}"
    return None


def _write_report(job_dir: Path, title: str, included, skipped, labels: dict, pdf: Path) -> None:
    lines = [f"# {labels['report']}: {title}", "", f"PDF: `{pdf.name}`", "",
             f"| {labels['page']} | {labels['subject']} | {labels['origin']} | {labels['status']} |",
             "|---|---|---|---|"]
    rows = [(p, labels["included"]) for p, _ in included] + \
           [(p, f"{labels['skipped']}: {r}") for p, r in skipped]
    for page, status in sorted(rows, key=lambda x: x[0]["n"]):
        final = page.get("final") or {}
        origin = _attribution(final, labels) or final.get("origin") or "—"
        lines.append(f"| {page['n']} | {page.get('caption') or page['subject']} | {origin} | {status} |")
    (job_dir / "report.md").write_text("\n".join(lines) + "\n")


def _slug(text: str) -> str:
    return re.sub(r"[^\w]+", "-", text.lower()).strip("-")[:40] or "coloring"
